### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by Mushoz** [Meorawr/LibFrameFade#1]
I am still getting `"Interface action blocked by an addon"` errors when trying to join BGs. One addon in particular is still causing it. It's this one: https://www.curseforge.com/wow/addons/missing-tradeskills-list

Is this one doing anything weird that's causing the taint?

**Comment by Meorawr** [comment]
That addon unfortunately is affected by dropdown menu taint as described in Thumbkin/MissingTradeSkillsList_TBC#15.

Depending on how you're joining battlegrounds:

- If you're joining via the "enter battle" button that appears in the dialog which pops up in the middle of the screen, this fixes that dialog and should make things work.
- If you're joining via the "enter battle" button in the right-click menu on the minimap icon for PvP queues, this doesn't fix that menu. The linked addon, due to using Blizzards' dropdown menu system, will break that menu most of the time just by having the addon loaded.
- If you've got SafeQueue installed, try disabling it. SafeQueue works by routing clicks through the dropdown menu of the PvP queue minimap icon, so could be broken by that addon being loaded as well.

Note that in an upcoming build of 2.5.2 (and 1.14.0) the underlying issue (Stanzilla/WoWUIBugs#169) will be fixed for the popup dialog, so workarounds such as this library shouldn't be needed. It won't, however, fix the dropdown menu issue to our knowledge.
