### ISSUE TITLE
LibFadeFrame is causing Elvui chat tabs to fade

### ISSUE THREAD

**Issue by telias82** [Meorawr/LibFrameFade#2]
see title

**Comment by Meorawr** [comment]
Should be fixed in the latest version (v3); other addons will pick up the fixed version eventually as part of their own release schedule. If needed, the fix can be applied right now by installing LibFrameFade as a standalone addon from any vendor of your choosing:

- [CurseForge](https://www.curseforge.com/wow/addons/libframefade)
- [Wago](https://addons.wago.io/addons/libframefade)
- [WoWInterface](https://www.wowinterface.com/downloads/info26143-LibFrameFade.html)
